/** Auto-generated by scripts/generate-gallery-photo-meta.mjs — do not edit */
export const GALLERY_PHOTO_META = {
  "mexico": {},
  "canada": {},
  "china": {
    "DSCF8154": {
      "takenAt": "2026-05-01T09:16:29.000Z",
      "camera": "FUJIFILM X-S20",
      "lens": "XF16-50mmF2.8-4.8 R LM WR",
      "focalLengthMm": 50,
      "focalLength35mm": 75,
      "aperture": 10,
      "shutter": "1/680",
      "iso": 640,
      "exposureComp": -0.33,
      "width": 6240,
      "height": 4160
    },
    "DSCF9906": {
      "takenAt": "2026-05-08T08:39:06.000Z",
      "camera": "FUJIFILM X-S20",
      "lens": "XF16-50mmF2.8-4.8 R LM WR",
      "focalLengthMm": 50,
      "focalLength35mm": 75,
      "aperture": 4.8,
      "shutter": "1/320",
      "iso": 1000,
      "exposureComp": -2.33,
      "width": 6240,
      "height": 4160
    },
    "auntie-cleaning": {
      "takenAt": "2026-05-08T04:19:04.000Z",
      "camera": "FUJIFILM X-S20",
      "lens": "XF16-50mmF2.8-4.8 R LM WR",
      "focalLengthMm": 34.3,
      "focalLength35mm": 51,
      "aperture": 5.6,
      "shutter": "1/320",
      "iso": 2500,
      "exposureComp": -0.67,
      "width": 6240,
      "height": 4160
    },
    "auntie-cooking": {
      "takenAt": "2026-05-08T04:26:02.000Z",
      "camera": "FUJIFILM X-S20",
      "lens": "XF16-50mmF2.8-4.8 R LM WR",
      "focalLengthMm": 19.6,
      "focalLength35mm": 29,
      "aperture": 6.4,
      "shutter": "1/320",
      "iso": 6400,
      "exposureComp": -0.67,
      "width": 6240,
      "height": 4160
    },
    "auntie-dance": {
      "takenAt": "2026-05-08T07:55:50.000Z",
      "camera": "FUJIFILM X-S20",
      "lens": "XF16-50mmF2.8-4.8 R LM WR",
      "focalLengthMm": 50,
      "focalLength35mm": 75,
      "aperture": 4.8,
      "shutter": "1/450",
      "iso": 640,
      "exposureComp": -0.33,
      "width": 6240,
      "height": 4160
    },
    "baozi": {
      "takenAt": "2026-05-09T05:07:05.000Z",
      "camera": "FUJIFILM X-S20",
      "lens": "XF16-50mmF2.8-4.8 R LM WR",
      "focalLengthMm": 20.2,
      "focalLength35mm": 30,
      "aperture": 4.5,
      "shutter": "1/640",
      "iso": 640,
      "exposureComp": -0.67,
      "width": 6240,
      "height": 4160
    },
    "bright-farmer": {
      "takenAt": "2026-04-30T09:39:55.000Z",
      "camera": "FUJIFILM X-S20",
      "lens": "XF16-50mmF2.8-4.8 R LM WR",
      "focalLengthMm": 16,
      "focalLength35mm": 24,
      "aperture": 10,
      "shutter": "1/400",
      "iso": 800,
      "exposureComp": -1.33,
      "width": 6240,
      "height": 4160
    },
    "building-ac": {
      "takenAt": "2026-05-09T06:53:27.000Z",
      "camera": "FUJIFILM X-S20",
      "lens": "XF16-50mmF2.8-4.8 R LM WR",
      "focalLengthMm": 27.9,
      "focalLength35mm": 42,
      "aperture": 7.1,
      "shutter": "1/1900",
      "iso": 320,
      "exposureComp": -1.67,
      "width": 6240,
      "height": 3512
    },
    "building-steps": {
      "takenAt": "2026-05-09T06:54:57.000Z",
      "camera": "FUJIFILM X-S20",
      "lens": "XF16-50mmF2.8-4.8 R LM WR",
      "focalLengthMm": 50,
      "focalLength35mm": 75,
      "aperture": 7.1,
      "shutter": "1/1500",
      "iso": 320,
      "exposureComp": -0.67,
      "width": 6240,
      "height": 3512
    },
    "card-uncs": {
      "takenAt": "2026-05-08T09:13:09.000Z",
      "camera": "FUJIFILM X-S20",
      "lens": "XF16-50mmF2.8-4.8 R LM WR",
      "focalLengthMm": 27.1,
      "focalLength35mm": 41,
      "aperture": 14,
      "shutter": "1/320",
      "iso": 10000,
      "exposureComp": -2,
      "width": 6240,
      "height": 4160
    },
    "cat": {
      "takenAt": "2026-05-07T05:24:16.000Z",
      "camera": "FUJIFILM X-S20",
      "lens": "XF16-50mmF2.8-4.8 R LM WR",
      "focalLengthMm": 39.6,
      "focalLength35mm": 59,
      "aperture": 10,
      "shutter": "1/400",
      "iso": 3200,
      "exposureComp": -0.33,
      "width": 6240,
      "height": 4160
    },
    "chess-table": {
      "takenAt": "2026-05-09T06:35:14.000Z",
      "camera": "FUJIFILM X-S20",
      "lens": "XF16-50mmF2.8-4.8 R LM WR",
      "focalLengthMm": 43.2,
      "focalLength35mm": 65,
      "aperture": 9,
      "shutter": "1/125",
      "iso": 400,
      "exposureComp": -0.67,
      "width": 6240,
      "height": 3512
    },
    "china-flags": {
      "takenAt": "2026-05-05T10:28:27.000Z",
      "camera": "FUJIFILM X-S20",
      "lens": "XF16-50mmF2.8-4.8 R LM WR",
      "focalLengthMm": 16,
      "focalLength35mm": 24,
      "aperture": 10,
      "shutter": "1/320",
      "iso": 12800,
      "exposureComp": 0.33,
      "width": 6240,
      "height": 4160
    },
    "chongqing-flipped": {
      "takenAt": "2026-05-08T12:22:42.000Z",
      "camera": "FUJIFILM X-S20",
      "lens": "XF16-50mmF2.8-4.8 R LM WR",
      "focalLengthMm": 27.9,
      "focalLength35mm": 42,
      "aperture": 5,
      "shutter": "1/320",
      "iso": 10000,
      "exposureComp": -2.33,
      "width": 6240,
      "height": 4160
    },
    "everyday-1": {
      "takenAt": "2026-05-05T10:32:01.000Z",
      "camera": "FUJIFILM X-S20",
      "lens": "XF16-50mmF2.8-4.8 R LM WR",
      "focalLengthMm": 35.3,
      "focalLength35mm": 53,
      "aperture": 8,
      "shutter": "1/400",
      "iso": 1250,
      "exposureComp": -0.33,
      "width": 6240,
      "height": 4160
    },
    "everyday-2": {
      "takenAt": "2026-05-05T10:30:03.000Z",
      "camera": "FUJIFILM X-S20",
      "lens": "XF16-50mmF2.8-4.8 R LM WR",
      "focalLengthMm": 50,
      "focalLength35mm": 75,
      "aperture": 20,
      "shutter": "1/170",
      "iso": 12800,
      "exposureComp": -0.33,
      "width": 6240,
      "height": 4160
    },
    "everyday-3": {
      "takenAt": "2026-05-05T10:30:12.000Z",
      "camera": "FUJIFILM X-S20",
      "lens": "XF16-50mmF2.8-4.8 R LM WR",
      "focalLengthMm": 50,
      "focalLength35mm": 75,
      "aperture": 8,
      "shutter": "1/400",
      "iso": 2500,
      "exposureComp": -0.33,
      "width": 6240,
      "height": 4160
    },
    "farmlands": {
      "takenAt": "2026-05-02T07:56:13.000Z",
      "camera": "FUJIFILM X-S20",
      "lens": "XF16-50mmF2.8-4.8 R LM WR",
      "focalLengthMm": 16,
      "focalLength35mm": 24,
      "aperture": 7.1,
      "shutter": "1/1100",
      "iso": 640,
      "exposureComp": -0.33,
      "width": 6240,
      "height": 4160
    },
    "fire": {
      "takenAt": "2026-05-01T10:09:56.000Z",
      "camera": "FUJIFILM X-S20",
      "lens": "XF16-50mmF2.8-4.8 R LM WR",
      "focalLengthMm": 47.2,
      "focalLength35mm": 71,
      "aperture": 5.6,
      "shutter": "1/400",
      "iso": 800,
      "exposureComp": -1,
      "width": 6240,
      "height": 4160
    },
    "furong-bridge-view": {
      "takenAt": "2026-05-02T15:32:19.000Z",
      "camera": "FUJIFILM X-S20",
      "lens": "XF16-50mmF2.8-4.8 R LM WR",
      "focalLengthMm": 26.3,
      "focalLength35mm": 39,
      "aperture": 6.4,
      "shutter": "1/110",
      "iso": 12800,
      "exposureComp": -1.67,
      "width": 6240,
      "height": 4160
    },
    "furong-town": {
      "takenAt": "2026-05-02T14:47:31.000Z",
      "camera": "FUJIFILM X-S20",
      "lens": "XF16-50mmF2.8-4.8 R LM WR",
      "focalLengthMm": 28.7,
      "focalLength35mm": 43,
      "aperture": 4,
      "shutter": "1/200",
      "iso": 12800,
      "exposureComp": -1,
      "width": 6240,
      "height": 4160
    },
    "goldfish": {
      "takenAt": "2026-05-08T09:20:25.000Z",
      "camera": "FUJIFILM X-S20",
      "lens": "XF16-50mmF2.8-4.8 R LM WR",
      "focalLengthMm": 50,
      "focalLength35mm": 75,
      "aperture": 5,
      "shutter": "1/320",
      "iso": 1250,
      "exposureComp": -1.67,
      "width": 6240,
      "height": 4160
    },
    "grungy-apartment": {
      "takenAt": "2026-05-08T09:21:13.000Z",
      "camera": "FUJIFILM X-S20",
      "lens": "XF16-50mmF2.8-4.8 R LM WR",
      "focalLengthMm": 50,
      "focalLength35mm": 75,
      "aperture": 7.1,
      "shutter": "1/320",
      "iso": 2500,
      "exposureComp": -1,
      "width": 6240,
      "height": 4160
    },
    "happy-woman": {
      "takenAt": "2026-05-08T04:18:38.000Z",
      "camera": "FUJIFILM X-S20",
      "lens": "XF16-50mmF2.8-4.8 R LM WR",
      "focalLengthMm": 50,
      "focalLength35mm": 75,
      "aperture": 5.6,
      "shutter": "1/320",
      "iso": 6400,
      "exposureComp": -0.67,
      "width": 6240,
      "height": 4160
    },
    "hole-in-the-wall": {
      "takenAt": "2026-05-08T14:56:38.000Z",
      "camera": "FUJIFILM X-S20",
      "lens": "XF16-50mmF2.8-4.8 R LM WR",
      "focalLengthMm": 17.5,
      "focalLength35mm": 26,
      "aperture": 5,
      "shutter": "1/320",
      "iso": 2500,
      "exposureComp": -2.33,
      "width": 6240,
      "height": 4160
    },
    "hotpot": {
      "takenAt": "2026-05-08T12:51:33.000Z",
      "camera": "FUJIFILM X-S20",
      "lens": "XF16-50mmF2.8-4.8 R LM WR",
      "focalLengthMm": 33.3,
      "focalLength35mm": 50,
      "aperture": 5,
      "shutter": "1/320",
      "iso": 2500,
      "exposureComp": -1.67,
      "width": 6240,
      "height": 4160
    },
    "lanterns-alley": {
      "takenAt": "2026-05-09T09:57:45.000Z",
      "camera": "FUJIFILM X-S20",
      "lens": "XF16-50mmF2.8-4.8 R LM WR",
      "focalLengthMm": 50,
      "focalLength35mm": 75,
      "aperture": 14,
      "shutter": "1/150",
      "iso": 4000,
      "exposureComp": -1.33,
      "width": 6240,
      "height": 4160
    },
    "mahjong": {
      "takenAt": "2026-05-09T07:06:01.000Z",
      "camera": "FUJIFILM X-S20",
      "lens": "XF70-300mmF4-5.6 R LM OIS WR",
      "focalLengthMm": 258.4,
      "focalLength35mm": 388,
      "aperture": 7.1,
      "shutter": "1/125",
      "iso": 640,
      "exposureComp": -0.67,
      "width": 6240,
      "height": 3512
    },
    "meituan-trio": {
      "takenAt": "2026-05-08T05:05:13.000Z",
      "camera": "FUJIFILM X-S20",
      "lens": "XF16-50mmF2.8-4.8 R LM WR",
      "focalLengthMm": 24.1,
      "focalLength35mm": 36,
      "aperture": 6.4,
      "shutter": "1/320",
      "iso": 800,
      "exposureComp": -0.67,
      "width": 6240,
      "height": 4160
    },
    "messy-balcony": {
      "takenAt": "2026-05-08T08:55:57.000Z",
      "camera": "FUJIFILM X-S20",
      "lens": "XF70-300mmF4-5.6 R LM OIS WR",
      "focalLengthMm": 300,
      "focalLength35mm": 450,
      "aperture": 5.6,
      "shutter": "1/320",
      "iso": 800,
      "exposureComp": -1.33,
      "width": 6240,
      "height": 4160
    },
    "mountain-range": {
      "takenAt": "2026-05-05T08:05:08.000Z",
      "camera": "FUJIFILM X-S20",
      "lens": "XF16-50mmF2.8-4.8 R LM WR",
      "focalLengthMm": 21.4,
      "focalLength35mm": 32,
      "aperture": 22,
      "shutter": "1/400",
      "iso": 1000,
      "exposureComp": -2,
      "width": 6240,
      "height": 4160
    },
    "mountain-scene": {
      "takenAt": "2026-05-01T04:45:23.000Z",
      "camera": "FUJIFILM X-S20",
      "lens": "XF16-50mmF2.8-4.8 R LM WR",
      "focalLengthMm": 20.8,
      "focalLength35mm": 31,
      "aperture": 22,
      "shutter": "1/400",
      "iso": 800,
      "exposureComp": -0.67,
      "width": 6240,
      "height": 4160
    },
    "park-gramps": {
      "takenAt": "2026-05-09T06:30:28.000Z",
      "camera": "FUJIFILM X-S20",
      "lens": "XF16-50mmF2.8-4.8 R LM WR",
      "focalLengthMm": 50,
      "focalLength35mm": 75,
      "aperture": 4.8,
      "shutter": "1/400",
      "iso": 640,
      "exposureComp": 0,
      "width": 6240,
      "height": 4160
    },
    "poles-in-farm": {
      "takenAt": "2026-05-02T08:44:12.000Z",
      "camera": "FUJIFILM X-S20",
      "lens": "XF16-50mmF2.8-4.8 R LM WR",
      "focalLengthMm": 50,
      "focalLength35mm": 75,
      "aperture": 7.1,
      "shutter": "1/1000",
      "iso": 2500,
      "exposureComp": -0.33,
      "width": 6240,
      "height": 4160
    },
    "rafting": {
      "takenAt": "2026-05-01T00:03:39.000Z",
      "camera": "FUJIFILM X-S20",
      "lens": "XF16-50mmF2.8-4.8 R LM WR",
      "focalLengthMm": 16,
      "focalLength35mm": 24,
      "aperture": 10,
      "shutter": "1/1700",
      "iso": 640,
      "exposureComp": -0.67,
      "width": 6240,
      "height": 4160
    },
    "rafts": {
      "takenAt": "2026-05-01T07:07:12.000Z",
      "camera": "FUJIFILM X-S20",
      "lens": "XF16-50mmF2.8-4.8 R LM WR",
      "focalLengthMm": 16,
      "focalLength35mm": 24,
      "aperture": 9,
      "shutter": "1/3000",
      "iso": 640,
      "exposureComp": -0.67,
      "width": 6240,
      "height": 4160
    },
    "rainy-chongqing": {
      "takenAt": "2026-05-08T11:26:35.000Z",
      "camera": "FUJIFILM X-S20",
      "lens": "XF16-50mmF2.8-4.8 R LM WR",
      "focalLengthMm": 27.9,
      "focalLength35mm": 42,
      "aperture": 6.4,
      "shutter": "1/320",
      "iso": 6400,
      "exposureComp": -1,
      "width": 6240,
      "height": 4160
    },
    "red-green": {
      "takenAt": "2026-05-09T06:36:10.000Z",
      "camera": "FUJIFILM X-S20",
      "lens": "XF16-50mmF2.8-4.8 R LM WR",
      "focalLengthMm": 40.8,
      "focalLength35mm": 61,
      "aperture": 9,
      "shutter": "1/140",
      "iso": 320,
      "exposureComp": -0.67,
      "width": 6240,
      "height": 3512
    },
    "robot-dog": {
      "takenAt": "2026-05-08T08:22:06.000Z",
      "camera": "FUJIFILM X-S20",
      "lens": "XF16-50mmF2.8-4.8 R LM WR",
      "focalLengthMm": 16,
      "focalLength35mm": 24,
      "aperture": 4.5,
      "shutter": "1/320",
      "iso": 1600,
      "exposureComp": -0.33,
      "width": 6240,
      "height": 4160
    },
    "roof-worker": {
      "takenAt": "2026-05-09T06:35:38.000Z",
      "camera": "FUJIFILM X-S20",
      "lens": "XF16-50mmF2.8-4.8 R LM WR",
      "focalLengthMm": 39.6,
      "focalLength35mm": 59,
      "aperture": 9,
      "shutter": "1/125",
      "iso": 640,
      "exposureComp": -0.67,
      "width": 6240,
      "height": 3512
    },
    "sleeping-cat": {
      "takenAt": "2026-05-07T09:14:04.000Z",
      "camera": "FUJIFILM X-S20",
      "lens": "XF16-50mmF2.8-4.8 R LM WR",
      "focalLengthMm": 33.3,
      "focalLength35mm": 50,
      "aperture": 4.5,
      "shutter": "1/400",
      "iso": 2500,
      "exposureComp": -0.67,
      "width": 6240,
      "height": 4160
    },
    "smoking": {
      "takenAt": "2026-05-09T07:01:40.000Z",
      "camera": "FUJIFILM X-S20",
      "lens": "XF16-50mmF2.8-4.8 R LM WR",
      "focalLengthMm": 39.6,
      "focalLength35mm": 59,
      "aperture": 7.1,
      "shutter": "1/300",
      "iso": 320,
      "exposureComp": -1,
      "width": 6240,
      "height": 3512
    },
    "stick-gramps": {
      "takenAt": "2026-05-09T06:32:27.000Z",
      "camera": "FUJIFILM X-S20",
      "lens": "XF16-50mmF2.8-4.8 R LM WR",
      "focalLengthMm": 50,
      "focalLength35mm": 75,
      "aperture": 4.8,
      "shutter": "1/750",
      "iso": 640,
      "exposureComp": 0.33,
      "width": 6240,
      "height": 4160
    },
    "thinking-cards": {
      "takenAt": "2026-05-08T09:10:01.000Z",
      "camera": "FUJIFILM X-S20",
      "lens": "XF16-50mmF2.8-4.8 R LM WR",
      "focalLengthMm": 16,
      "focalLength35mm": 24,
      "aperture": 4,
      "shutter": "1/320",
      "iso": 1250,
      "exposureComp": -1.33,
      "width": 6240,
      "height": 4160
    },
    "two-dudes": {
      "takenAt": "2026-05-09T09:34:07.000Z",
      "camera": "FUJIFILM X-S20",
      "lens": "XF70-300mmF4-5.6 R LM OIS WR",
      "focalLengthMm": 300,
      "focalLength35mm": 450,
      "aperture": 8,
      "shutter": "1/2400",
      "iso": 640,
      "exposureComp": -1.67,
      "width": 6240,
      "height": 4160
    },
    "winding-bus": {
      "takenAt": "2026-05-05T07:38:38.000Z",
      "camera": "FUJIFILM X-S20",
      "lens": "XF70-300mmF4-5.6 R LM OIS WR",
      "focalLengthMm": 177.9,
      "focalLength35mm": 267,
      "aperture": 22,
      "shutter": "1/400",
      "iso": 1250,
      "exposureComp": -0.67,
      "width": 6240,
      "height": 4160
    },
    "winding-roads": {
      "takenAt": "2026-05-05T05:08:09.000Z",
      "camera": "FUJIFILM X-S20",
      "lens": "XF16-50mmF2.8-4.8 R LM WR",
      "focalLengthMm": 27.1,
      "focalLength35mm": 41,
      "aperture": 13,
      "shutter": "1/1100",
      "iso": 640,
      "exposureComp": -1.67,
      "width": 6240,
      "height": 4160
    },
    "window-gramps": {
      "takenAt": "2026-05-08T09:08:03.000Z",
      "camera": "FUJIFILM X-S20",
      "lens": "XF70-300mmF4-5.6 R LM OIS WR",
      "focalLengthMm": 137,
      "focalLength35mm": 206,
      "aperture": 5,
      "shutter": "1/320",
      "iso": 2000,
      "exposureComp": -0.67,
      "width": 6240,
      "height": 4160
    },
    "window": {
      "takenAt": "2026-05-09T07:25:52.000Z",
      "camera": "FUJIFILM X-S20",
      "lens": "XF16-50mmF2.8-4.8 R LM WR",
      "focalLengthMm": 47.2,
      "focalLength35mm": 71,
      "aperture": 5,
      "shutter": "1/1250",
      "iso": 640,
      "exposureComp": -4,
      "width": 6240,
      "height": 4160
    }
  },
  "japan": {
    "asakusa": {
      "takenAt": "2025-03-07T20:31:08.000Z",
      "camera": "NIKON D3400",
      "width": 6016,
      "height": 4016
    },
    "banners": {
      "takenAt": "2025-03-07T20:54:08.000Z",
      "camera": "NIKON D3400",
      "width": 4016,
      "height": 6016
    },
    "beach": {
      "takenAt": "2025-03-09T20:52:47.000Z",
      "camera": "NIKON D3400",
      "width": 6016,
      "height": 4016
    },
    "buddha-shrine": {
      "takenAt": "2025-02-09T19:33:04.000Z",
      "camera": "NIKON D3400",
      "width": 4016,
      "height": 6016
    },
    "business-man": {
      "takenAt": "2025-03-12T18:25:40.000Z",
      "camera": "NIKON D3400",
      "width": 6016,
      "height": 4016
    },
    "cats": {
      "takenAt": "2025-03-01T20:14:02.000Z",
      "camera": "NIKON D3400",
      "width": 6016,
      "height": 4016
    },
    "deer": {
      "takenAt": "2025-03-03T20:29:09.000Z",
      "camera": "NIKON D3400",
      "width": 6016,
      "height": 4016
    },
    "door-deer": {
      "takenAt": "2025-03-03T20:31:02.000Z",
      "camera": "NIKON D3400",
      "width": 6016,
      "height": 4016
    },
    "festival-object": {
      "takenAt": "2025-02-25T18:37:09.000Z",
      "camera": "NIKON D3400",
      "width": 4016,
      "height": 6016
    },
    "frozen-castle": {
      "takenAt": "2025-02-12T18:23:02.000Z",
      "camera": "NIKON D3400",
      "width": 4016,
      "height": 6016
    },
    "green-bar": {
      "takenAt": "2025-03-15T07:28:22.000Z",
      "camera": "NIKON D3400",
      "width": 4016,
      "height": 6016
    },
    "hiroshima": {
      "takenAt": "2025-03-02T19:28:11.000Z",
      "camera": "NIKON D3400",
      "width": 6016,
      "height": 4016
    },
    "iceberg": {
      "takenAt": "2025-03-01T19:46:19.000Z",
      "camera": "NIKON D3400",
      "width": 6016,
      "height": 4016
    },
    "jugs": {
      "takenAt": "2025-02-25T15:47:15.000Z",
      "camera": "NIKON D3400",
      "width": 6016,
      "height": 4016
    },
    "lanterns": {
      "takenAt": "2025-02-09T06:13:33.000Z",
      "camera": "NIKON D3400",
      "width": 6016,
      "height": 4016
    },
    "long-stick": {
      "takenAt": "2025-02-12T18:33:34.000Z",
      "camera": "NIKON D3400",
      "width": 4016,
      "height": 6016
    },
    "mini-shrine": {
      "takenAt": "2025-02-09T19:55:53.000Z",
      "camera": "NIKON D3400",
      "width": 6016,
      "height": 4016
    },
    "monks": {
      "takenAt": "2025-02-09T19:40:30.000Z",
      "camera": "NIKON D3400",
      "width": 6016,
      "height": 4016
    },
    "nest": {
      "takenAt": "2025-02-26T19:28:29.000Z",
      "camera": "NIKON D3400",
      "width": 6016,
      "height": 4016
    },
    "night-restaurant": {
      "takenAt": "2025-03-02T23:53:15.000Z",
      "camera": "NIKON D3400",
      "width": 6016,
      "height": 4016
    },
    "night-signs": {
      "takenAt": "2025-03-15T07:35:16.000Z",
      "camera": "NIKON D3400",
      "width": 4016,
      "height": 6016
    },
    "ocean-kid": {
      "takenAt": "2025-03-01T20:55:13.000Z",
      "camera": "NIKON D3400",
      "width": 6016,
      "height": 4016
    },
    "ocean-roads": {
      "takenAt": "2025-03-14T21:09:52.000Z",
      "camera": "NIKON D3400",
      "width": 6016,
      "height": 4016
    },
    "old-man": {
      "takenAt": "2025-03-02T19:35:42.000Z",
      "camera": "NIKON D3400",
      "width": 6016,
      "height": 4016
    },
    "pigeons": {
      "takenAt": "2025-03-09T20:40:11.000Z",
      "camera": "NIKON D3400",
      "width": 6016,
      "height": 4016
    },
    "purple-bar": {
      "takenAt": "2025-03-15T07:29:45.000Z",
      "camera": "NIKON D3400",
      "width": 6016,
      "height": 4016
    },
    "river-mountains": {
      "takenAt": "2025-02-09T04:05:50.000Z",
      "camera": "NIKON D3400",
      "width": 6016,
      "height": 4016
    },
    "river-students": {
      "takenAt": "2025-03-02T21:56:41.000Z",
      "camera": "NIKON D3400",
      "width": 6016,
      "height": 4016
    },
    "running-kid": {
      "takenAt": "2025-03-14T20:40:56.000Z",
      "camera": "NIKON D3400",
      "width": 4016,
      "height": 6016
    },
    "sakura": {
      "takenAt": "2025-02-26T19:25:45.000Z",
      "camera": "NIKON D3400",
      "width": 6016,
      "height": 4016
    },
    "shrine": {
      "takenAt": "2025-02-05T21:19:00.000Z",
      "camera": "NIKON D3400",
      "width": 6016,
      "height": 4016
    },
    "snow-roots": {
      "takenAt": "2025-02-09T04:15:17.000Z",
      "camera": "NIKON D3400",
      "focalLengthMm": 31,
      "focalLength35mm": 46,
      "aperture": 4.2,
      "shutter": "1/25",
      "iso": 100,
      "exposureComp": 0.3333333333333333,
      "width": 4000,
      "height": 6000
    },
    "snow-temple": {
      "takenAt": "2025-02-09T19:44:44.000Z",
      "camera": "NIKON D3400",
      "width": 6016,
      "height": 4016
    },
    "sunset": {
      "takenAt": "2025-03-14T21:38:46.000Z",
      "camera": "NIKON D3400",
      "width": 6016,
      "height": 4016
    },
    "takoyaki": {
      "takenAt": "2025-03-01T04:24:19.000Z",
      "camera": "NIKON D3400",
      "width": 6016,
      "height": 4016
    },
    "taxi": {
      "takenAt": "2025-03-14T20:24:03.000Z",
      "camera": "NIKON D3400",
      "width": 4016,
      "height": 6016
    },
    "tori-gates": {
      "takenAt": "2025-03-01T18:49:17.000Z",
      "camera": "NIKON D3400",
      "width": 6016,
      "height": 4016
    },
    "tori": {
      "takenAt": "2025-02-05T21:19:31.000Z",
      "camera": "NIKON D3400",
      "width": 6016,
      "height": 4016
    },
    "train": {
      "takenAt": "2025-03-01T18:44:56.000Z",
      "camera": "NIKON D3400",
      "width": 6016,
      "height": 4016
    },
    "tree-shadows": {
      "takenAt": "2025-02-24T20:44:13.000Z",
      "camera": "NIKON D3400",
      "width": 4016,
      "height": 6016
    },
    "trees": {
      "takenAt": "2025-02-09T04:13:46.000Z",
      "camera": "NIKON D3400",
      "width": 6016,
      "height": 4016
    },
    "venusaur": {
      "takenAt": "2025-02-24T20:47:56.000Z",
      "camera": "NIKON D3400",
      "width": 6016,
      "height": 4016
    }
  }
};

/** @returns {import('../galleryPhotoMetaFormat.js').GalleryPhotoMeta | null} */
export function galleryPhotoMeta(region, name) {
  return GALLERY_PHOTO_META[region]?.[name] ?? null;
}
