/** Auto-generated by scripts/generate-gallery-aspect-ratios.mjs — do not edit */
export const GALLERY_ASPECT_RATIOS = {
  "mexico": {
    "art-museum": {
      "w": 1600,
      "h": 2400
    },
    "bakery": {
      "w": 2400,
      "h": 1600
    },
    "bike-leaves": {
      "w": 1600,
      "h": 2400
    },
    "bikes": {
      "w": 2400,
      "h": 1600
    },
    "blue-door": {
      "w": 1600,
      "h": 2400
    },
    "coke-store": {
      "w": 1600,
      "h": 2400
    },
    "flowers": {
      "w": 1600,
      "h": 2400
    },
    "fruit-store": {
      "w": 1600,
      "h": 2400
    },
    "fruit-vendor": {
      "w": 1600,
      "h": 2400
    },
    "green-wall": {
      "w": 1600,
      "h": 2400
    },
    "meat-vendor": {
      "w": 1600,
      "h": 2400
    },
    "museum-reflection": {
      "w": 1600,
      "h": 2400
    },
    "museum-roof": {
      "w": 2400,
      "h": 1600
    },
    "old-man": {
      "w": 1600,
      "h": 2400
    },
    "orange-wall": {
      "w": 2400,
      "h": 1600
    },
    "palace": {
      "w": 2400,
      "h": 1600
    },
    "palm-trees": {
      "w": 1600,
      "h": 2400
    },
    "pastor-tacos": {
      "w": 1600,
      "h": 2400
    },
    "playground": {
      "w": 1600,
      "h": 2400
    },
    "plaza-garibaldi": {
      "w": 2400,
      "h": 1600
    },
    "pool": {
      "w": 2400,
      "h": 1600
    },
    "street-stalls": {
      "w": 2400,
      "h": 1600
    },
    "street-vendor": {
      "w": 1600,
      "h": 2400
    },
    "sunset-dark": {
      "w": 4160,
      "h": 6240
    },
    "taco-vendor": {
      "w": 2400,
      "h": 1600
    },
    "tree-reflection": {
      "w": 2400,
      "h": 1600
    },
    "windmill": {
      "w": 6240,
      "h": 4160
    }
  },
  "canada": {
    "autumn-pond": {
      "w": 1067,
      "h": 1600
    },
    "blurred-rain": {
      "w": 1600,
      "h": 1067
    },
    "boat-cabin": {
      "w": 1067,
      "h": 1600
    },
    "brick-tower": {
      "w": 1600,
      "h": 1067
    },
    "cans": {
      "w": 1600,
      "h": 1067
    },
    "cargo-cranes": {
      "w": 1600,
      "h": 1067
    },
    "chinatown-market": {
      "w": 1067,
      "h": 1600
    },
    "chongqing-restaurant": {
      "w": 1067,
      "h": 1600
    },
    "container-ship": {
      "w": 1600,
      "h": 1067
    },
    "empty-goalpost": {
      "w": 1600,
      "h": 1067
    },
    "fallen-leaves": {
      "w": 1067,
      "h": 1600
    },
    "farm-ca": {
      "w": 1600,
      "h": 1067
    },
    "ferry-lookout": {
      "w": 1600,
      "h": 1067
    },
    "firework": {
      "w": 1600,
      "h": 1066
    },
    "fish-vendor": {
      "w": 1067,
      "h": 1600
    },
    "flower-lamppost": {
      "w": 1067,
      "h": 1600
    },
    "fruit-worker": {
      "w": 1600,
      "h": 1067
    },
    "gated-alley": {
      "w": 1067,
      "h": 1600
    },
    "golden-grass": {
      "w": 1600,
      "h": 1067
    },
    "golden-maples": {
      "w": 1067,
      "h": 1600
    },
    "golden-spires": {
      "w": 1066,
      "h": 1600
    },
    "graffiti-alley": {
      "w": 1067,
      "h": 1600
    },
    "hotdog-stand": {
      "w": 1067,
      "h": 1600
    },
    "leaves-glow": {
      "w": 1067,
      "h": 1600
    },
    "moon": {
      "w": 1600,
      "h": 1067
    },
    "nootka-court": {
      "w": 1067,
      "h": 1600
    },
    "orca": {
      "w": 1067,
      "h": 1600
    },
    "pacific-railway": {
      "w": 1067,
      "h": 1600
    },
    "parliament-flowers": {
      "w": 1067,
      "h": 1600
    },
    "peach-roses": {
      "w": 1600,
      "h": 1067
    },
    "pink-jellyfish": {
      "w": 1600,
      "h": 1067
    },
    "port-cranes": {
      "w": 1600,
      "h": 1067
    },
    "rainy-roses": {
      "w": 1600,
      "h": 1067
    },
    "scrap-sculpture": {
      "w": 1067,
      "h": 1600
    },
    "street-protester": {
      "w": 1600,
      "h": 1067
    },
    "sun-rays": {
      "w": 1600,
      "h": 1067
    },
    "sunset-seagull": {
      "w": 1600,
      "h": 1067
    },
    "totem-pole": {
      "w": 1067,
      "h": 1600
    },
    "totem-top": {
      "w": 1067,
      "h": 1600
    },
    "towering-cloud": {
      "w": 1067,
      "h": 1600
    },
    "walking-dog": {
      "w": 1600,
      "h": 949
    },
    "war-memorial": {
      "w": 1067,
      "h": 1600
    },
    "wet-leaves": {
      "w": 1600,
      "h": 1067
    },
    "wheat": {
      "w": 1600,
      "h": 1067
    },
    "windows-xp-grass": {
      "w": 1600,
      "h": 1066
    }
  },
  "china": {
    "auntie-cleaning": {
      "w": 6240,
      "h": 4160
    },
    "auntie-cooking": {
      "w": 5926,
      "h": 3950
    },
    "auntie-dance": {
      "w": 5953,
      "h": 3969
    },
    "baozi": {
      "w": 6240,
      "h": 4160
    },
    "bright-farmer": {
      "w": 6240,
      "h": 4160
    },
    "building-ac": {
      "w": 3512,
      "h": 6240
    },
    "building-steps": {
      "w": 6066,
      "h": 3414
    },
    "card-uncs": {
      "w": 4160,
      "h": 6240
    },
    "cat": {
      "w": 5604,
      "h": 3736
    },
    "chess-table": {
      "w": 6240,
      "h": 3512
    },
    "china-flags": {
      "w": 6240,
      "h": 4160
    },
    "chongqing-flipped": {
      "w": 6111,
      "h": 4074
    },
    "everyday-1": {
      "w": 4160,
      "h": 6240
    },
    "everyday-2": {
      "w": 4068,
      "h": 6103
    },
    "everyday-3": {
      "w": 4160,
      "h": 6240
    },
    "farmlands": {
      "w": 6240,
      "h": 4160
    },
    "fire": {
      "w": 6240,
      "h": 4160
    },
    "furong-bridge-view": {
      "w": 5712,
      "h": 3808
    },
    "furong-town": {
      "w": 4160,
      "h": 6240
    },
    "goldfish": {
      "w": 5051,
      "h": 3367
    },
    "grungy-apartment": {
      "w": 4160,
      "h": 6240
    },
    "happy-woman": {
      "w": 4160,
      "h": 6240
    },
    "hole-in-the-wall": {
      "w": 6240,
      "h": 4160
    },
    "hotpot": {
      "w": 6240,
      "h": 4160
    },
    "lanterns-alley": {
      "w": 4160,
      "h": 6240
    },
    "mahjong": {
      "w": 5316,
      "h": 2992
    },
    "meituan-trio": {
      "w": 6240,
      "h": 4160
    },
    "messy-balcony": {
      "w": 6240,
      "h": 4160
    },
    "mountain-range": {
      "w": 4160,
      "h": 6240
    },
    "mountain-scene": {
      "w": 5988,
      "h": 3992
    },
    "park-gramps": {
      "w": 3899,
      "h": 5849
    },
    "poles-in-farm": {
      "w": 6240,
      "h": 4160
    },
    "rafting": {
      "w": 6240,
      "h": 4160
    },
    "rafts": {
      "w": 6240,
      "h": 4160
    },
    "rainy-chongqing": {
      "w": 6240,
      "h": 4160
    },
    "red-green": {
      "w": 2928,
      "h": 5203
    },
    "robot-dog": {
      "w": 5441,
      "h": 3627
    },
    "roof-worker": {
      "w": 3512,
      "h": 6240
    },
    "sleeping-cat": {
      "w": 6240,
      "h": 4160
    },
    "smoking": {
      "w": 6240,
      "h": 3512
    },
    "stick-gramps": {
      "w": 2773,
      "h": 4160
    },
    "temple": {
      "w": 4160,
      "h": 6240
    },
    "thinking-cards": {
      "w": 6240,
      "h": 4160
    },
    "two-dudes": {
      "w": 5812,
      "h": 3875
    },
    "winding-bus": {
      "w": 4160,
      "h": 6240
    },
    "winding-roads": {
      "w": 4160,
      "h": 6240
    },
    "window-gramps": {
      "w": 5998,
      "h": 3998
    },
    "window": {
      "w": 6240,
      "h": 4160
    },
    "zhangjiajie": {
      "w": 3854,
      "h": 5781
    }
  },
  "japan": {
    "asakusa": {
      "w": 6016,
      "h": 4016
    },
    "banners": {
      "w": 4016,
      "h": 6016
    },
    "beach": {
      "w": 6016,
      "h": 4016
    },
    "boats": {
      "w": 5496,
      "h": 3664
    },
    "buddha-shrine": {
      "w": 3738,
      "h": 5600
    },
    "business-man": {
      "w": 4932,
      "h": 3292
    },
    "cats": {
      "w": 5663,
      "h": 3780
    },
    "colorful-shrine": {
      "w": 4016,
      "h": 6016
    },
    "deer": {
      "w": 5687,
      "h": 3796
    },
    "door-deer": {
      "w": 6016,
      "h": 4016
    },
    "festival-object": {
      "w": 4016,
      "h": 6016
    },
    "flowers": {
      "w": 1221,
      "h": 2400
    },
    "frozen-castle": {
      "w": 4016,
      "h": 6016
    },
    "green-bar": {
      "w": 4016,
      "h": 6016
    },
    "hiroshima": {
      "w": 5957,
      "h": 3976
    },
    "iceberg": {
      "w": 5912,
      "h": 3946
    },
    "jugs": {
      "w": 5826,
      "h": 3889
    },
    "lanterns": {
      "w": 5759,
      "h": 3844
    },
    "long-stick": {
      "w": 4016,
      "h": 6016
    },
    "mini-shrine": {
      "w": 6016,
      "h": 4016
    },
    "monks": {
      "w": 5449,
      "h": 3637
    },
    "nest": {
      "w": 6016,
      "h": 4016
    },
    "night-restaurant": {
      "w": 6016,
      "h": 4016
    },
    "night-signs": {
      "w": 3858,
      "h": 5780
    },
    "ocean-kid": {
      "w": 6016,
      "h": 4016
    },
    "ocean-roads": {
      "w": 6016,
      "h": 4016
    },
    "old-man": {
      "w": 4581,
      "h": 3058
    },
    "path": {
      "w": 4016,
      "h": 6016
    },
    "pigeons": {
      "w": 6016,
      "h": 4016
    },
    "purple-bar": {
      "w": 6016,
      "h": 4016
    },
    "river-mountains": {
      "w": 6016,
      "h": 4016
    },
    "river-students": {
      "w": 6016,
      "h": 4016
    },
    "running-kid": {
      "w": 4016,
      "h": 6016
    },
    "sakura": {
      "w": 6016,
      "h": 4016
    },
    "shrine": {
      "w": 6016,
      "h": 4016
    },
    "snow-roots": {
      "w": 4000,
      "h": 6000
    },
    "snow-temple": {
      "w": 2452,
      "h": 3674
    },
    "sunset": {
      "w": 1788,
      "h": 2679
    },
    "takoyaki": {
      "w": 6016,
      "h": 4016
    },
    "taxi": {
      "w": 4016,
      "h": 6016
    },
    "tori-gates": {
      "w": 6016,
      "h": 4016
    },
    "tori": {
      "w": 6016,
      "h": 4016
    },
    "train": {
      "w": 6016,
      "h": 4016
    },
    "tree-shadows": {
      "w": 3300,
      "h": 4943
    },
    "trees": {
      "w": 6016,
      "h": 4016
    },
    "venusaur": {
      "w": 6016,
      "h": 4016
    }
  }
};

/** @returns {{ w: number; h: number } | null} */
export function galleryPhotoDimensions(region, name) {
  return GALLERY_ASPECT_RATIOS[region]?.[name] ?? null;
}
